export const ACCOUNT_NOT_FOUND = 'No account found. Please sign-up.'
export const ACCOUNT_EXISTS = 'Account already exists. Please sign-in or reset your password.'
export const INVALID_CREDENTIALS = 'Invalid credentials'
export const ACCOUNT_CREATED = 'A confirmation email has been sent out to your email address.'
export const PASSWORD_CHANGE_REQUEST_CREATED = 'A password reset email has been sent out to your email address.'
export const TOKEN_INVALID = 'TOKEN INVALID'
